apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-app
  labels:
    commit: 4ca160fd05c003e5067fd6d9c8213656b24b962c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
        commit: 4ca160fd05c003e5067fd6d9c8213656b24b962c
    spec:
      containers:
      - name: product-catalog-app-container
        image: derekoneil/alpha-office-product-catalog:master-4ca160fd05c003e5067fd6d9c8213656b24b962c
        imagePullPolicy: Always
        ports:
        - name: pc-app-port
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-app
    commit: 4ca160fd05c003e5067fd6d9c8213656b24b962c
spec:
  ports:
  - port: 30000
    nodePort: 30000
    targetPort: 80
  selector:
    app: product-catalog-app
    commit: 4ca160fd05c003e5067fd6d9c8213656b24b962c
  type: LoadBalancer
---
